SAMPLE_RECIPES = [
    {
        "name": "Chocolate Cake",
        "ingredients": [
            {"name": "flour", "quantity": 2, "unit_cost": 30},
            {"name": "sugar", "quantity": 1, "unit_cost": 20},
            {"name": "cocoa", "cost": 50},
        ],
        "batch_size": 10,
        "equipment": ["mixer", "oven", "cooling_rack"],
        "target_margin": 30,
        "target_price": 260,
    },
    {
        "name": "Vanilla Muffin",
        "ingredients": [
            {"name": "flour", "quantity": 1.5, "unit_cost": 25},
            {"name": "vanilla", "cost": 35},
            {"name": "butter", "quantity": 1, "unit_cost": 60},
        ],
        "batch_size": 12,
        "equipment": ["mixer", "oven"],
        "target_margin": 30,
        "target_price": 240,
    },
    {
        "name": "Lemon Tart",
        "ingredients": [
            {"name": "lemon", "quantity": 2, "unit_cost": 18},
            {"name": "cream", "quantity": 1, "unit_cost": 95},
            {"name": "pastry_shell", "cost": 70},
        ],
        "batch_size": 8,
        "equipment": ["oven", "cooling_rack"],
        "target_margin": 30,
        "target_price": 210,
    },
    {
        "name": "Garlic Bread",
        "ingredients": [
            {"name": "bread", "quantity": 10, "unit_cost": 8},
            {"name": "garlic_butter", "cost": 55},
        ],
        "batch_size": 10,
        "equipment": ["oven"],
        "target_margin": 25,
        "target_price": 220,
    },
    {
        "name": "Protein Cookie",
        "ingredients": [
            {"name": "protein_powder", "quantity": 2, "unit_cost": 180},
            {"name": "oats", "quantity": 1, "unit_cost": 45},
            {"name": "honey", "cost": 85},
        ],
        "batch_size": 10,
        "equipment": ["mixer", "oven"],
        "target_margin": 30,
        "target_price": 420,
    },
    {
        "name": "Fruit Parfait",
        "ingredients": [
            {"name": "yogurt", "quantity": 2, "unit_cost": 55},
            {"name": "berries", "quantity": 1, "unit_cost": 120},
            {"name": "granola", "cost": 45},
        ],
        "batch_size": 6,
        "equipment": ["mixer"],
        "target_margin": 35,
        "target_price": 360,
    },
    {
        "name": "Brownie Bites",
        "ingredients": [
            {"name": "chocolate", "quantity": 2, "unit_cost": 130},
            {"name": "flour", "quantity": 1, "unit_cost": 30},
            {"name": "sugar", "quantity": 1, "unit_cost": 25},
        ],
        "batch_size": 16,
        "equipment": ["mixer", "oven", "cooling_rack"],
        "target_margin": 30,
        "target_price": 500,
    },
    {
        "name": "Cinnamon Roll",
        "ingredients": [
            {"name": "dough", "quantity": 2, "unit_cost": 70},
            {"name": "cinnamon", "cost": 25},
            {"name": "icing", "quantity": 1, "unit_cost": 50},
        ],
        "batch_size": 9,
        "equipment": ["mixer", "oven"],
        "target_margin": 30,
        "target_price": 320,
    },
    {
        "name": "No Bake Energy Bar",
        "ingredients": [
            {"name": "oats", "quantity": 2, "unit_cost": 45},
            {"name": "peanut_butter", "quantity": 1, "unit_cost": 90},
            {"name": "dates", "cost": 75},
        ],
        "batch_size": 12,
        "equipment": ["mixer", "cooling_rack"],
        "target_margin": 30,
        "target_price": 330,
    },
    {
        "name": None,
        "ingredients": [
            {"name": "rice", "quantity": 2, "unit_cost": 40},
            {"name": "vegetables", "cost": 60},
        ],
        "batch_size": 10,
        "equipment": ["oven"],
        "target_margin": 30,
        "target_price": 210,
    },
]
